# See https://redoc.ly/docs/cli/configuration/ for more information.
apiDefinitions:
  main: openapi/openapi.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: warning
referenceDocs:
  htmlTemplate: ./docs/index.html
  theme:
    colors:
      primary:
        main: "#9f3232"
    typography:
      fontFamily: "Courier New, monospace"
    headings:
      fontFamily: "Courier New, monospace"
    rightPanel:
      backgroundColor: "#583636"
