name: Deploy to Nekoweb

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build redocly static page
        run: |
          mkdir build
          npx @redocly/cli build-docs openapi/openapi.yaml -o build/index_test.html
          cp docs/favicon.ico build/favicon_test.ico
  
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./build

      - name: Deploy to Nekoweb
        uses: mp-pinheiro/nekoweb-deploy@0.2.0
        with:
          API_KEY: ${{ secrets.API_KEY }}
          BUILD_DIR: './build'
          DEPLOY_DIR: '/'
          CLEANUP: 'False'
          DELAY: '0.5'
          NEKOWEB_PAGENAME: 'fairfruit'
